### ISSUE TITLE
Flagrum Mod doesn't seem to replace a specific file when sending to others. 

### ISSUE THREAD

**Issue by canplx** [Kizari/Flagrum#146] opened 2024-03-26 23:50 UTC
I created a VFX mod for the warp abilites. however it seems that the main warp does replace with another file when put into a Flagrum mod. Some of the the files have references and some don't but it looks like none of them work others regardless. 

I could send the mod file if you would like to take a look at it

**Comment by Rinual** [comment] 2024-03-27 23:29
Can you provide like 100x more context and info? Think there was a template for the issue that would help if you followed

**Comment by canplx** [comment] 2024-03-28 17:37
Hey sorry, only reason I didn't follow the template is because it's really for replicating the issue. I believe this specific issue doesn't have any problems for the creator of the Flagrum mod, but for others who use the exported mod. Which Is why I said I can give you the file.  


Basically, this is the main warp for the game. I have replaced it with another VFX file already present in the game. It also has a reference file added to it, but regardless of adding the reference to it. (because the main VFX don't need references) The warp VFX still doesn't seem to appear for others: 
![gotcha](https://github.com/Kizari/Flagrum/assets/139719648/b58f38ce-41f3-4563-a0ed-c9fac5f6961b)


This is how the warp VFX should appear: 
![Final Fantasy XV Windows Edition Screenshot 2024 03 22 - 22 11 35 77](https://github.com/Kizari/Flagrum/assets/139719648/651a5970-c141-448f-b645-b8a380f5ce70)


But I think most people will only see the glow effect when warping which in build list is the: 
![next](https://github.com/Kizari/Flagrum/assets/139719648/d25cb85f-ca45-4e36-879b-b2f9da92b473)


Here is the file I'm working with just in case:  
[smoke_-_vfx_replacement_.zip](https://github.com/Kizari/Flagrum/files/14793467/smoke_-_vfx_replacement_.zip)

Here are some other effects to compare it to as well: 
[VFX Warp 1.1 modpack.zip](https://github.com/Kizari/Flagrum/files/14793474/VFX.Warp.1.1.modpack.zip)

Please let me know if you need more information.

**Comment by Rinual** [comment] 2024-03-29 03:35
Not entirely sure I know what the issue is, or why its only become an issue for this mod as even other .vfx mods seem fine currently such as the weapons vfx mod. But i cant really confirm from this that there even is a bug without rebuilding your mod locally instead of from the .fmod installation to see if other factors are in play. We've had similar issues with modders where it worked on their end and no one elses, and they had similar thoughts, but once they reinstalled their game for example, even locally their mod was no longer working. The game just be weird like that sometimes, but that hasnt been an issue since 1.5 stopped changing the files directly. But to tell if this is an issue with the .fmod + .ffg flagrum fragment files that are used instead of the original assets you are replacing directly with, there would need to be a way to confirm that. Preferably, have a single file traced back to where you know this *one* file, when used as a direct replacement works, but when installed as an .fmod, does not. 

On a related note about the first part of your response, but not relevant to fixing this issue; References arent exactly as clear cut as if the original asset didnt need one, the one you are replacing it with wont need it either, for example, that reference is a .vfx file, but that .vfx file expects certain shaders, materials, any related .gmdl and texture for those to load as well, so its not a matter of, well the original didnt need references, as their can be other resources that should be that arent. Not saying thats the case here, though EPA content is a prime example of things that will almost always need references. You can open up a .vfx file if you are curious in a hex editor and you will find some strings with asset uri's as examples of things the vfx is expecting to find in memory. But usually referencing the parent .ebex file of that vfx like i think you did, is all you would need anyways, so this is not exactly relevant for troubleshooting, just thought id mention it incase it helped later with something. 

But yeah, narrowing down what file you can confirm works locally installed with a direct replacement, but no longer works when installed from a .fmod is really going to be the best bet of having anything be fixable, assuming that the same behavior is something we can replicate on our end.

**Comment by canplx** [comment] 2024-03-31 15:15
Alright I will probably just look into this problem more myself man. It could be that I have to many effects at play in one mod or they are just conflicting. If I don't get it working no big deal.

**Comment by Rinual** [comment] 2024-03-31 16:36
Probably the best strat till there is something easier / definite to look into.

**Comment by Kizari** [comment] 2024-05-07 21:39
Closing this for now since there's seemingly nothing to address. Feel free to reopen if more information becomes available.

**Closed by Kizari** 2024-05-07 21:39 UTC
Labels: bug, information needed, flagrum

**Comment by Rinual** [comment] 2024-08-04 05:31
The issue was discovered to be related to the mod targeting files that were also getting replaced by the 4k Pack DLC, without the mod targeting the 4k files as well. 

Though that DLC usually only targets textures for models and characters, it can also change other files such as .VFX files. Other users experiencing similar issues should ensure they utilize the free DLC, and test with and without 4k assets on, to make sure the mod works for both versions of the game.

**Comment by canplx** [comment] 2024-08-16 15:19
Another possible reason for this is if someone has another mod installed targeting the same .earc archive. Having two of the same .earc will seemingly cancel out the VFX from the mod.
