### ISSUE TITLE
Problems with environment export (Missing files, weird normal shading) in new versions of Flagrum.

### ISSUE THREAD

**Issue by Larxian** [Kizari/Flagrum#123] opened 2024-01-09 04:35 UTC
Hello.

I noticed that there is an issue with the environment export tool in the recent versions of Flagrum. 
The environment export feature was gone for a few weeks / month because of a bug, and since it's been added back, it has issues that were not there before. 

When exporting / importing an environment into Blender, there are now a lot of missing models, and the normals look very strange, almost like cell shading? 

As example, when exporting "area_ravettrice", the export done with Flagrum **v1.5.5** is only **11.2 gb**, while the export done with **v1.4.11** (the last version I have that still exports fine for me) is **18.4 gb**.

Here are some screenshots showing the differences.
v1.4.11:
![v1 4](https://github.com/Kizari/Flagrum/assets/14320479/2edcde2e-320c-4ab3-bad4-9f03b44d63a4)
v1.5.5:
![v1 5](https://github.com/Kizari/Flagrum/assets/14320479/2c2863b8-82df-4cc3-9b6d-6cb18a4d9200)
v1.4.11:
![v1 4_2](https://github.com/Kizari/Flagrum/assets/14320479/f2414b0c-6e99-412d-a6cd-65d212af0a0e)
v1.5.5:
![v1 5_2](https://github.com/Kizari/Flagrum/assets/14320479/13d11719-2e69-4a0b-beec-d4cc245aefbe)

I think that's all the informations I could report on that, but if you need anything else let me know. I thought this was worth reporting because it seems like a major issue, unless it's just me being affected? Not sure. For the moment I'm using the older version offline (to keep it from updating) because it's what works the best for me.

**Comment by Kizari** [comment] 2024-01-09 05:35
Hi Larxian, thanks for your report.

Which version of Blender are you using to import the environments? I know there have been shading issues with some versions, 3.1 is one example, but I'm not sure of the exhaustive list unfortunately. I know it should work fine on 3.0 though, unless this bug was caused by the exporter in Flagrum 1.5+ and not on the Blender side.

Let me know and I'll be happy to look into it and get it fixed up for the next Flagrum patch.

**Comment by Larxian** [comment] 2024-01-09 06:42
The version of Blender I'm using is 3.4.1, which is importing assets exported from Flagrum 1.4.11 fine.
I just tried with Blender 3.0 to verify if there was any difference, the shading issue is the same :
![3 0](https://github.com/Kizari/Flagrum/assets/14320479/5ab43973-3d8d-4659-89ed-de6c0e9d55e3)

It's also not just a problem on Blender's side since like I mentionned the scene exported from the current version of Flagrum is smaller in size.
Surprisngly, the amount of files exported is actually the same, but the size of the files are different, here's a quick example:

Files exported from v1.4 (working correctly):
![files 1 4](https://github.com/Kizari/Flagrum/assets/14320479/7895e544-f16f-47f1-959e-f3e6c68f6192)

Files exported from v1.5 (missing objects in blender and weird shading):
![files 1 5](https://github.com/Kizari/Flagrum/assets/14320479/77d3e2f3-e7ba-4885-a4c2-d6953e883323)

**Comment by Kizari** [comment] 2024-01-09 06:49
Thanks for the extra information, that's really helpful. I have a hunch as to what might be going wrong here. Will let you know if I need any further information, but should be good from here.

**Comment by Larxian** [comment] 2024-01-09 06:52
No problem and thank you! I hope it won't be too much of an headache for you.

**Comment by Kizari** [comment] 2024-01-09 06:55
It's always a gamble with XV, it'll either be a super simple 5 minute fix, or some nonsensical nightmare that takes a whole day. Either way, I'll manage 😄

**Comment by Kizari** [comment] 2024-01-20 00:05
I can confirm the shading is messed up for me using a Flagrum 1.5.5 export with Flagrum-Blender 1.3.3 in Blender 3.0 (which it hadn't been under that same setup with Flagrum 1.4 exports). I'm not however missing any models in the `group_galdin` export I did. Did you notice missing models on any smaller exports? Any of the larger areas such as full regions or cities tend to take several hours to run a single test, so it would be really helpful if you have run into it somewhere smaller.

**Comment by Larxian** [comment] 2024-01-20 08:05
Hey, so I tried exporting Galdin to give you a point of comparison. I never exported it before so I'm not sure if anything is missing, doesn't seem like it, unless it's supposed to have some terrain in it.
![Sans titre](https://github.com/Kizari/Flagrum/assets/14320479/d74a03a5-ecd8-4fb1-b683-79643bfc4f70)
It came out at 1,47gb, 2455 objects in the scene.

As for area_revattrice, like I mentionned in my original post, the export folder is indeed much smaller, 11,2 GB instead of 18,4 GB for the correct version. 
The models folder is almost the same size, there is a small difference, but curiously the broken export is actually the heavier one. 2,44 GB for the broken export, 2,42 GB for the correct export.
The biggest size difference is with the texture folders, the one from the faulty export (from Flagrum 1.5.5) is 8.76 GB, while the texture folder from the correct export is 16 GB, almost twice the size.

Could it be that there is a problem with the material export and Blender skips the objects with missing textures during the import?

**Comment by Kizari** [comment] 2024-01-20 14:14
Thank you. Your Galdin looks exactly the same as mine, nothing missing but messed up vertex normals. It's strange to see that there are so many missing models from Altissia when the models folder size is almost identical. Even more strange because the only thing I changed about the environment exporter in 1.5 was updating it to use the new gmdl.gfxbin reader. I would imagine that could be responsible for the shading problems, but I don't see how it could cause missing models.

You have a good point about the materials though, but unfortunately that didn't lead to anything when I checked just now. The whole import would crash if a material failed to import since the environment exporter doesn't have per-model exception handling like the gmdl importer. Actually, I wonder if that is what happened? It's possible an exception did occur part way through your Altissia import and that's why there are models missing from the scene despite the model folder having the same number of files and nearly the same size? It's hard to notice when that's the case, because Blender sometimes only flashes the error for half a second then buries it so you don't even notice anything went wrong, especially with something like an environment import where Blender ends up minimised for hours. Might also explain why Galdin is fine since it has fewer moving parts to potentially cause an exception.

I guess I'll try solve the normals issue first. I may just have to bite the bullet and do some Altissia tests myself once that's done. Not much I can do without a log from Blender that explains why it's shitting itself.

**Comment by Kizari** [comment] 2024-01-20 15:49
Managed to solve the normals issue. Unfortunately it won't solve the missing models issue though, so going to need to test on Altissia.

**Comment by Larxian** [comment] 2024-01-20 16:46
It's nice that you managed to fix the normal issue.
For Altissia, you could probably just try with a smaller part of the city? Like map_ravettrice_altissia_a or something, I imagine the issue would be the same, I can try if you want.

**Comment by Larxian** [comment] 2024-01-20 17:27
Okay so I exported a few scenes from both versions of flagrum, here are the results: 
"map_ravettrice_altissia_a" doesn't show any difference in the amount of objects, only shader issue.
1.4:
![A 1 4](https://github.com/Kizari/Flagrum/assets/14320479/78ca0471-a83f-4791-b859-0c5f50320d66)
1.5:
![A 1 5](https://github.com/Kizari/Flagrum/assets/14320479/91e7d0b0-de11-47ad-85f0-7912e11a68ae)

From there I was afraid how many scenes I would have to test to see the issue happen, but "thankfully", "**map_ravettrice_altissia_b**" is where issues start.

1.4:
![B 1 4](https://github.com/Kizari/Flagrum/assets/14320479/6568a3b1-07ae-4756-b27a-5a9740064235)
1.5:
![B 1 5](https://github.com/Kizari/Flagrum/assets/14320479/1400cf88-2f16-4a19-b18e-89759b3da49e)

The whole map isn't needed to find missing objects, and maybe the fact that the first map doesn't have any missing stuff but the second does can somehow help too? I don't know, but I hope this will help you!

**Comment by Kizari** [comment] 2024-01-20 17:55
Ahh, thanks for that. Had already started doing the whole thing, and it did indeed throw an error. Good to know I can focus on a single sector though when I have to retest after attempting to fix things.

I am curious, do you get a bunch of "Failed to load" errors when you import the 1.4.X export into Blender? You can go to `Window > Show System Console` to see this.

![image](https://github.com/Kizari/Flagrum/assets/25322543/96a14c15-9b9c-4b05-a7ae-9f3fd9b0b092)

Everything starting from "TypeError" is the error that causes the import to fail and is why there is a bunch of stuff missing. You wouldn't see this on the 1.4.X export, so only interested to know if the "Failed to load" errors present there, as it may also be a cause of missing models if not.

This error should help me solve the problem though, it seems the UV data of one or more models is corrupted in the 1.5.X export.

**Comment by Larxian** [comment] 2024-01-20 18:06
I don't have any TypeError, however I do have the "Failed to load data" on a few things.
![error](https://github.com/Kizari/Flagrum/assets/14320479/1adae53a-8542-467e-a8ba-c041ba0c1c59)

**Comment by Kizari** [comment] 2024-01-20 19:42
Okay yeah that's great news. Seems like it's just this one problem to solve now and then all should be in good working order.

**Comment by Kizari** [comment] 2024-01-24 23:59
Found an example of a model that was causing the crash:
```
data://environment/altissia/props/al_ar_town03/models/al_ar_town03_typec.gmdl
```
Unfortunately, that model imports fine when I load it with the standard `.gfxbin` import option, so I can't even troubleshoot it that way. Must be something to do with the way its data is read and packed up in the environment exporter. Will take a look at the data that outputs and see if I can spot anything unusual.

**Comment by Kizari** [comment] 2024-01-25 00:37
Found it! The UV maps on that model in the environment export have some UV coordinates that are non-numeric. Most likely caused by a change to the `gfxbin` reader in Flagrum 1.5 to not automatically force non-numeric floats to 0.0 since this is handled elsewhere these days. Bit of an oversight on my part to not realise it'd affect the environment exporter in this way. Getting it fixed now.

**Comment by Kizari** [comment] 2024-01-25 02:00
There we go. Picture taken from a Flagrum 1.5.6 (development version) export of map_ravettrice_altissia_b. Matches your 1.4.X export perfectly from what I can see. Will release this with the rest of 1.5.6 as soon as it's done, shouldn't be far away.

**Closed by Kizari** 2024-01-25 02:00 UTC
Labels: bug, blender add-on

**Comment by Larxian** [comment] 2024-01-25 10:06
Oh great!! Glad to hear you could fix it and thank you :)
It's not urgent for me since I've been using 1.4 to go around the issue, but it for sure will be more convenient now, and most importantly I think it will be good for other people who would start using Flagrum now and wouldn't have any idea of what's happening.

**Comment by Kizari** [comment] 2024-01-25 23:16
Totally agree. It'll be nice for you to not have to hold your Flagrum back so you can make the most of new features and fixes too. Thanks again for bringing the issue to my attention and for your help with diagnosing the problem, I really appreciate it. ❤️

**Comment by Larxian** [comment] 2024-01-26 10:57
No problem! I'm glad if I could be of any help and thank you again for all the work you do for XV :)
