### ISSUE TITLE
Crash from Deleting Loose File Instructions

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#66] opened 2023-04-20 16:53 UTC
After saving a mod that adds loose files to the game, removing those instructions result in the following error. 

<code>Object reference not set to an instance of an object.
   at Flagrum.Web.Features.ModManager.Editor.EditorLooseFileRow.<BuildRenderTree>b__0_0() in C:\Code\Flagrum-Patreon\Flagrum.Web\Features\ModManager\Editor\EditorLooseFileRow.razor:line 42
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)</code>
   
   The only way to remove those instructions is to fully delete the mod the mod and rebuild with the corrections.

**Comment by Kizari** [comment] 2023-04-24 00:59
This was caused by me forgetting to pass a reference to the Editor component to the EditorLooseFileRow as a CascadingParameter.

When attempting to call the RemoveLooseFile method on the parent Editor, the null reference exception was being thrown as Parent was null.

This is fixed in Flagrum 1.4.9.

**Closed by Kizari** 2023-04-24 00:59 UTC
Labels: bug, flagrum
