### ISSUE TITLE
Forspoken Btex Conversion for basic image types failing

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#125] opened 2024-01-15 20:48 UTC
**Describe the bug**
Mods replacing textures in Forspoken come out broken, frequently looking in part like a normal map more than the original diffuse. 

**To Reproduce**
replace `data://asset/character/hu/hu000/model_512/sourceimages/hu000_512_base_mant_1001_b_$h.tif` with this black and white filtered version of the same texture
![hu000_512_base_mant_1001_b_h](https://github.com/Kizari/Flagrum/assets/108095289/898adfbe-131e-4844-981d-0f3d7587f5cd)

**Expected behavior**
it should look like 
![image](https://github.com/Kizari/Flagrum/assets/108095289/a5f1a11b-c509-46dd-9c4c-4547518d014e)

what it actually looks like 
![image](https://github.com/Kizari/Flagrum/assets/108095289/f40c8ee8-a3ce-4dd0-8963-f5c3be74fdeb)

presumably btex converter broke during an update at some point. glaive yay

**Comment by Lennn888** [comment] 2024-01-15 21:28
A little more information:

- previously created replacements seem to work properly (latest known working texture mod: 08/29/2023)
- .btex to .btex replacement is still working to this day.

**Comment by Rinual** [comment] 2024-01-15 21:45
> Reference

ya, none of those others need btex *conversion* as the fmod already has it in btex

**Comment by Kizari** [comment] 2024-01-18 20:21
I'm guessing I broke this when I did the huge refactor for 1.5. Forspoken BTEX is rather cursed, so it's kinda difficult to diagnose these problems. Best bet is to cross-reference the pre-1.5 code, but of course that can be difficult since there are 3 different BTEX converters in pre-1.5 (FFXV PC, FFXV PS4, and Forspoken PC) while there is only one unified converter in 1.5. The pre-1.5 BTEX converters are also just profoundly cursed since it was some of the first pieces of code I wrote when beginning modding, so yeah, that's always fun to try and cross-reference.

**Comment by Kizari** [comment] 2024-01-25 23:07
Yeah, I messed up with the 1.5 code. I did account for the SEDB header after all, but I forgot to go back through and add the DirectStorage partitioning for the pixel data that FFXV doesn't have.

There still seems to be a problem with the BTEX reader as well though, which was something I looked into around 1.5.3 but couldn't figure out. Will try again now.

**Comment by Kizari** [comment] 2024-01-26 00:01
Oh kidding, it's funnier than that. I did actually add the Forspoken specifics, it's just that I forgot to pass the profile type (i.e. Forspoken) to the asset converter in the 1.5 mod builder pipeline and so it was compiling the textures in the FFXV format. Well umm...oops. At least that's an easy fix in theory. Now to figure out why the reader is playing up.

**Comment by Kizari** [comment] 2024-01-26 03:25
(Really just leaving this here for my own benefit so I have these notes in case something like this happens in future).

Wow that was something.

My code was using `Stream.CopyTo(Stream destination, int bufferSize)` to copy the blocks of data from the Forspoken BTEX into a `MemoryStream` that holds the data in a form that is compatible with DDS (i.e. no DirectStorage segmentation and no padding between images).

The problem is, the above `Stream.CopyTo` will copy the entire stream to the destination stream, using a buffer of the given size. What it was meant to be doing, and what I thought it was doing, was copying the given number of bytes (bufferSize) to the destination stream. The reason I thought it was doing this is because I have my own custom extension method with the definition `Stream.CopyTo(Stream destination, long count)` which does behave as needed. I presume this was an oversight when I was rewriting BTEX for 1.5 where I thought I was using this method, but it was actually resolving the other one because I needed to cast the `blockSize` to `long` for it to use the one I wanted.

Anyway, after adding that cast, it works just as well as it did in pre-1.5 now.

**Closed by Kizari** 2024-01-26 03:25 UTC
Labels: bug, help wanted, flagrum, forspoken
