### ISSUE TITLE
Can't enable/disable/create Steam Workshop mod in Flagrum 

### ISSUE THREAD

**Issue by canplx** [Kizari/Flagrum#120] opened 2023-12-13 23:42 UTC
Getting hit with consistent error "Flagrum has encountered fatal error and must now close". 

This happened when I tried to delete my mod that was uploaded to steam workshop 

I have also gone through the steps of re indexing my game files, force cleanup, reinstalling Flagrum and I have also reinstalled the game entirely. 

The mod still appears in my workshop tab even though I have unsubscribed from it and deleted within steam.

**Comment by Kizari** [comment] 2023-12-14 03:56
I had this problem a while back regarding my own mods. Not sure what causes Steam to get in that state, but even deleting it manually from the Steam Workshop folder didn't help as Steam would just redownload it when I went to launch the game. This was despite me having unsubscribed from it. I actually had to manually remove the entry from the `.acf` file in the Steam Workshop folder for FFXV to finally get it to stop redownloading it. No idea why Steam does this, but it's just one of its many fun bugs.

As for why Flagrum crashed, I would need you to upload your crash log(s) from `%LOCALAPPDATA%\Flagrum\crashes` to be able to diagnose what went wrong there.

**Comment by canplx** [comment] 2023-12-14 16:28
[2023-12-13_05-36-20-5664_crash_110505157.txt](https://github.com/Kizari/Flagrum/files/13675844/2023-12-13_05-36-20-5664_crash_110505157.txt)
[2023-12-14_10-25-33-3003_crash_1445299886.txt](https://github.com/Kizari/Flagrum/files/13675845/2023-12-14_10-25-33-3003_crash_1445299886.txt)


Here is the crash log files.

**Comment by Kizari** [comment] 2023-12-15 06:03
Okay it's crashing because there are multiple Steam Workshop mods with the same name on your system. I could have sworn this came up in the past and I did something to prevent it crashing in this case, but I guess I must have forgotten or something. I would assume this is happening if you have a local copy of one of your Steam Workshop mods from creating it, and also a workshop copy from subscribing to that same mod after uploading it. You'd want to get rid of the workshop copy since you need to hold on to the local copy in case you ever want to update the mod in future.

Presuming this is the same mod you're trying to delete in the previous comments, then that's all you'd need to do to fix the crashing. The problem is, you need to be able to get into Flagrum and open the mod card to find the UUID to be able to identify which mod it is in the `.acf` file...

Actually, there's another way. If you launch FFXV and go into the "Mod" menu on the title screen, you can disable all mods except the one you want the UUID for. Then if you close the game and open your binmod.list, all of the mods in the list should say "False" next to them except for the one you left enabled. That one will have the UUID you need. Keep in mind there are two lots of True/False for each entry in binmod.list, it's only the first one in each row you care about.

I can't remember if the `.acf` file uses the UUID or the folder name the mod is inside. If it's not the UUID, then you can see the folder number in the full file path for the workshop mod in binmod.list. Once you have that, you should be able to delete that folder, remove the `.acf` entry for the mod, and then it should finally be gone.

**Comment by canplx** [comment] 2023-12-15 16:34
Hey thanks so much man, turning off the mod from the title screen actually worked. I don't know why I didn't think of that, but yea that allowed me to get rid of the mods and create some. 

Thanks again.

**Comment by Kizari** [comment] 2023-12-15 18:39
You're most welcome. I'll leave this issue open to remind myself to fix the issue where Flagrum crashes when subscribing to your own mods, but it seems everything else is sorted now. Have fun!

**Comment by Kizari** [comment] 2024-01-19 23:18
This should be fixed in Flagrum 1.5.6.

**Closed by Kizari** 2024-01-19 23:18 UTC
Labels: bug, operational, flagrum
