### ISSUE TITLE
[Bug]: Fatal Error & Infinite indexing?

### ISSUE THREAD

**Issue by DarkLordAries** [Kizari/Flagrum#168] opened 2024-10-11 17:22 UTC
### Operating System

Windows 11 64-Bit

### Game Version

Latest Steam Release

### Version

1.5.14

### Description of the bug

So I'm encountering two issues;
1st: In my initial install of Flagrum 1.5.14 it didn't find my exe, so I set the proper exe for FFXV and it just indexed and never found it. Waited for over an hour. I went into the settings and tried both options for regenerate and force reset. No avail. I closed the mod manager and loaded it and it seems it went away? But if I click regenerate it still never stops indexing?
Manager was installed with virus protection off, and windows exclusion added. PC specs are 5950x cpu, RTX 3090FE, and M.2 SSD. Game was fresh installed and verified integrity through steam.

2nd: Idk if its because of the previous issue, but if I close it out it allows me to install FFXV mods, and ingame it seems so far that some are working. Haven't been able to check all yet, but if I click on any mod in the manager it "Fatal error" needs to restart.

### Steps to reproduce the bug

1st problem: Go to settings, click Regenerate File index. Never finishes indexing.

2nd problem: Go to mod manager, Click any FFXV mod and automatically Fatal Errors with force restart.

### Crash logs

[2024-10-11_01-02-58-9941_crash_543010736.txt](https://github.com/user-attachments/files/17345760/2024-10-11_01-02-58-9941_crash_543010736.txt)

### Code of Conduct

- [X] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [X] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [X] I confirm that I am using a legitimate copy of the game.
- [X] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [X] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Rinual** [comment] 2024-10-12 05:14
yeah the crashlog corresponds to not having a properly indexed filelist for the game. Indexing usually only takes like 5 - 10 minutes max on an m.2, so something is certainly off.

This might already be the case, if you hadnt touched any mods for FFXV or used other programs like special K or something. But:
Make sure you have a clean installation of the game before indexing, i always recommend deleting the game installation folder entirely like is suggested here https://github.com/Kizari/Flagrum/wiki/Using-the-Mod-Manager

Granted, if mods are still working somehow, and you dont plan on making mods or browsing game files, i guess this is skippable? But you *don't* need to disable your virus scan to use flagrum, the installation .exe can get flagged due to its [unsigned nature of the code](https://github.com/Kizari/Flagrum/issues/102)

But my hope is, there is just some random file that shouldnt be in your game folder chilling there, and a clean installation might fix it. At least, that's my best guess..

**Comment by DarkLordAries** [comment] 2024-10-14 14:08
> yeah the crashlog corresponds to not having a properly indexed filelist for the game. Indexing usually only takes like 5 - 10 minutes max on an m.2, so something is certainly off.
> 
> This might already be the case, if you hadnt touched any mods for FFXV or used other programs like special K or something. But: Make sure you have a clean installation of the game before indexing, i always recommend deleting the game installation folder entirely like is suggested here https://github.com/Kizari/Flagrum/wiki/Using-the-Mod-Manager
> 
> Granted, if mods are still working somehow, and you dont plan on making mods or browsing game files, i guess this is skippable? But you _don't_ need to disable your virus scan to use flagrum, the installation .exe can get flagged due to its [unsigned nature of the code](https://github.com/Kizari/Flagrum/issues/102), but you can keep it enabled as long as the installation file isn't deleted.
> 
> But my hope is, there is just some random file that shouldnt be in your game folder chilling there, and a clean installation might fix it. At least, that's my best guess..

Yeah before touching the mods, I uninstalled the gamec deleted its game folder, fresh installed and verified integrity before installing Flagram. It seems to work even with the issue at hand so "fck it" as they say lololol. Only mod that doesn't work for me is the latest "No collisions" so I'll take that as a blessing considering the circumstances. In this particular game I don't think I'll be attempting to make a mod or browse the game files, so for now I guess we can consider this solved. Thanks for such a speedy reply and sorry for the late comment myself. Haven't been able to touch my game since I last posted this! Cheers Mate!!!

**Comment by Rinual** [comment] 2024-10-14 15:18
np, as for the no collisions, it isn't *every* collision, so if you are looking to confirm that one isn't working as well, if / when you re in Altissia, try going off the side of the pier / boardwalk into the water. 

Sorry for the issues, glad it isn't stopping you from having fun with mods though =)

**Comment by DarkLordAries** [comment] 2024-10-15 18:30
> np, as for the no collisions, it isn't _every_ collision, so if you are looking to confirm that one isn't working as well, if / when you re in Altissia, try going off the side of the pier / boardwalk into the water.
> 
> Sorry for the issues, glad it isn't stopping you from having fun with mods though =)

Hmmm I haven't gotten that far, but I'll reinstall once I get closer. It's my first play through so I've only just gotten the first royal weapon after the invasion :D

And its okay, its generally not the creators fault. Theres so many versions of windows, M.2 SSD's, etc that its hard to make it perfect it for all. P.S. I just installed your Mod menu and the avatara unock with avatara creation is BAD ASS.

**Comment by Kizari** [comment] 2024-12-21 01:34
Closing this as the issue author is satisfied with the solution and I am unable to reproduce the issue. If anyone else encounters this issue and has more information on how to reproduce, please open a new issue.

**Closed by Kizari** 2024-12-21 01:34 UTC
Labels: bug
