### ISSUE TITLE
Flagrum crash on startup: "The output char buffer is too small to contain the decoded characters"

### ISSUE THREAD

**Issue by lonelyCrowDE** [Kizari/Flagrum#85] opened 2023-08-12 21:24 UTC
Flagrum already takes about an 1 hour and 20 min to index but nothing happens.
if i try to update my EXE patch flagrum will crash with "An unhandled error has occured"

Game and Flagrum are installed on Windows main SSD

Flagrum Crash log:
[crash.txt](https://github.com/Kizari/Flagrum/files/12328314/crash.txt)

![Screenshot 2023-08-12 195038](https://github.com/Kizari/Flagrum/assets/142121611/de32111a-dd1c-4199-adce-35a857d02917)

**Comment by Kizari** [comment] 2023-08-12 21:30
It looks like one or more of your FFXV files are corrupted. If you use Steam, try verify the integrity of the game files to restore any corrupted files, then try again.

**Comment by lonelyCrowDE** [comment] 2023-08-12 21:35
I already tried this but it didnt worked.
and just got another error 
![Screenshot 2023-08-12 233249](https://github.com/Kizari/Flagrum/assets/142121611/10feeae5-f2d8-45b7-aa13-4fe0c03c9b31)

**Comment by Kizari** [comment] 2023-08-13 13:32
Are there any earc files in your game data directory or any of its subdirectories that didn't originally ship with the game? If so, those will need to be removed manually as verifying files via Steam won't clear them.

If not, you may need to uninstall the game, delete any residual files from the FFXV directory in your steam library (NOT the one in My Documents with your saves), and then reinstall it. Verifying files can sometimes fail to detect and repair files, we've seen this happen before with at least three different people.

**Comment by Kizari** [comment] 2023-08-14 23:29
Closing this as the issue has been resolved. While multiple issues can cause an error message like this, if caused by corruption, it should be solved as outlined in the comments above. If you encounter this error and the cause is not the same, please open a new issue with as much detail as possible.

**Closed by Kizari** 2023-08-14 23:29 UTC
Labels: operational, flagrum
