### ISSUE TITLE
MOD not WORKING

### ISSUE THREAD

**Issue by kaioken32** [Kizari/Flagrum#121] opened 2024-01-08 14:23 UTC
MOD not working when activated
using the latest version of flagrum

it used to work before, the latest one not activating any mod

**Comment by Kizari** [comment] 2024-01-09 01:08
The Flagrum 1.5+ mod loader only works on the latest FFXV build from Steam. If you are using an exe from a different game store or an older version, it may not work for you. The reason for this is that the new mod loader doesn't alter any of the original game files which speeds up the process and removes the potential for file corruption, but unfortunately requires that specific executable to function correctly.

**Comment by Kizari** [comment] 2024-01-09 01:32
Possibly related: #93 #110

**Comment by kaioken32** [comment] 2024-01-09 05:46
> The Flagrum 1.5+ mod loader only works on the latest FFXV build from Steam. If you are using an exe from a different game store or an older version, it may not work for you. The reason for this is that the new mod loader doesn't alter any of the original game files which speeds up the process and removes the potential for file corruption, but unfortunately requires that specific executable to function correctly.

How is that same exe worked for old flagrum but new one is not working? 
Can you look into this further?

**Comment by Kizari** [comment] 2024-01-09 06:52
> The reason for this is that the new mod loader doesn't alter any of the original game files which speeds up the process and removes the potential for file corruption, but unfortunately requires that specific executable to function correctly.

**Comment by kaioken32** [comment] 2024-01-09 07:29
> > The reason for this is that the new mod loader doesn't alter any of the original game files which speeds up the process and removes the potential for file corruption, but unfortunately requires that specific executable to function correctly.

That's what I said, it is the same latest version exe file from FFXV, and it did not work with the latest flagrum, how can I donwload  old flagrum if you have the link?

**Comment by kaioken32** [comment] 2024-01-13 11:56
> > The reason for this is that the new mod loader doesn't alter any of the original game files which speeds up the process and removes the potential for file corruption, but unfortunately requires that specific executable to function correctly.

So yeah, sorry for the other post
As things go, I luckily had the old downloaded version of flagrum which was 1.4.10

I installed it and it functions same as 1.5+
This time With 1.4.10,  the mods work, and tested

So it is probably not ffxv exe file problem that you assumed 
Most probably a issue With the latest version of flagrum
Kindly look into it

**Comment by Rinual** [comment] 2024-01-15 19:48
> So it is probably not ffxv exe file problem that you assumed
> Most probably a issue With the latest version of flagrum
> Kindly look into it

Not sure how to more directly say you are wrong besides saying you are wrong. Please don't be rude to the developer of the tools and naively guess where the issue is. 

1.5 has introduced a new method of how mods are applied, that dont involve changing the original files. Reverting to an old version of flagrum reverts those changes back to when corrupting the game files still could happen when using mods. 

Kindly, I am closing this issue, while you catch up and re-read what the developer has already said, and learn how your conclusion and his statement are not mutually exclusive.

**Closed by Rinual** 2024-01-15 19:48 UTC
Labels: bug

**Comment by kaioken32** [comment] 2024-01-17 05:39
> > So it is probably not ffxv exe file problem that you assumed
> > Most probably a issue With the latest version of flagrum
> > Kindly look into it
> 
> Not sure how to more directly say you are wrong besides saying you are wrong. Please don't be rude to the developer of the tools and naively guess where the issue is.
> 
> 1.5 has introduced a new method of how mods are applied, that dont involve changing the original files. Reverting to an old version of flagrum reverts those changes back to when corrupting the game files still could happen when using mods.
> 
> Kindly, I am closing this issue, while you catch up and re-read what the developer has already said, and learn how your conclusion and his statement are not mutually exclusive.

It is indeed mutually exclusive and I know what he meant, I asked you people to find a solution that works for all exe and YES I am using STEAM and it DOESNT work, so I don't get what you are talking about here, NEXT time BE A MAN and READ replies LIKE A MAN, don't excuse your lazy development and just directly say that "I don't care what happens to issues, deal with it or leave it" like a coward

**Comment by katekittaly** [comment] 2024-01-18 23:42
Let's try this again with small words so you will be able to read this like a man.

1.4: Take all exe
1.5: Take only latest real exe

This on purpose. Do not like? YOU look into it.

**Comment by Vaan749** [comment] 2024-01-19 13:12
I have the same problem like you
Kaioken32 can you send me the old version of flagrum

**Comment by Kizari** [comment] 2024-01-19 15:08
@kaioken32 Unfortunately for you, this is not a customer service helpdesk, so you don't get to rudely demand that people find solutions to your problems. I am always happy to do my best to resolve issues and make Flagrum the best it can be, but I won't give up my free time for people that think it's okay to treat me or any of the other repository maintainers like that. Using Flagrum is a privilege I kindly grant to the community, which has taken thousands of hours out of my life. I hope you will keep that in mind when interacting with volunteers in future. Treating them kindly and with respect will get you a lot further. You have been blocked from interacting any further with this repository, as your presence here has been very destructive, and I simply don't want to waste any more of my time dealing with it when I could be using that time to improve Flagrum instead.

If anyone else is experiencing this issue on the latest official Steam release, please create a new issue with as much detail as possible and I'll be happy to look into it. Do **not** open an issue if you are not using the latest **legitimate** Steam executable on 64-bit WIndows, as there is nothing I can do to fix the mod loader on other executables that I don't own—it will only waste both of our time. You may however open an issue to discuss potentially supporting other executables if you have a compelling reason that it should be supported.
