### ISSUE TITLE
Missing Files from Earcs being reported while Exporting Env files

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#56] opened 2023-04-08 23:05 UTC
Couple of reports from users, including one who had freshly reinstalled the game having flagrum crash while exporting various environment files. 

[crash.txt](https://github.com/Kizari/Flagrum/files/11184402/crash.txt)
[crash (1).txt](https://github.com/Kizari/Flagrum/files/11184404/crash.1.txt)

These environments seem to export fine on other machines, but how the files became missing while no mods are active is still under investigation. 

Users that encounter this issue are encouraged to validate their game files or make a fresh reinstall and export their needed files prior to enabling any mods.

**Comment by Kizari** [comment] 2023-04-16 16:52
Possibly caused by #57

**Comment by Rinual** [comment] 2023-04-20 22:21
Quick way to replicate: 
Enable and disable mogfest
Export `area_duscae.ebex` as a .fed
Crash quickly enough that
 this isnt a time loss. 

New logs actually list files having issues
[Log.txt](https://github.com/Kizari/Flagrum/files/11290814/Log.txt)
[crash.txt](https://github.com/Kizari/Flagrum/files/11290815/crash.txt)

**Comment by Kizari** [comment] 2023-04-20 23:08
After checking the URI associated with the hash in the crash log, it became apparent that the Moogle Chocobo Carnival mod has some errors. Some of the "Add File" instructions use URIs that already exist in game (it should either be replacing the file, or omitted from the mod), which is causing those files to be deleted when the mod is disabled. The end result is that these files are then missing from the game and so anything that needs to operate on them causes Flagrum to crash (and likely causes issues in game as well).

To any users reading this, it would be best to disable the mod and restore the original game files by following the instructions [here](https://github.com/Kizari/Flagrum/wiki/Using-the-Mod-Manager#fixing-a-broken-game).

**Developer Notes**

The fix to this problem is simply to update the mod before the final release so these URI conflicts are no longer present. However, Flagrum should also be updated to ensure such instructions can't be added to mods so this doesn't happen in future.

**Comment by Kizari** [comment] 2023-04-24 02:48
URI conflicts for add instructions are now detected and prevented in Flagrum 1.4.9.

The Moogle Chocobo Carnival issue itself will be fixed in the official mod release.

**Closed by Kizari** 2023-04-24 02:48 UTC
Labels: enhancement, operational, flagrum
