### ISSUE TITLE
Flagrum Crashes while building MODS - Access is denied

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#60] opened 2023-04-19 04:46 UTC
Periodically some users report issues with Flagrum suddenly crashing when trying to create a brand new mod, save their changes to an existing mod or attempt to delete a mod. 

The following error is displayed in Flagrum's [crash.txt](https://github.com/Kizari/Flagrum/files/11268630/crash.txt)

Usually this state is temporary, though sometimes it will not have the most recent change saved. However simply re-entering the mod and saving it will usually fix the issue, though sometimes it will require 10+ attempts.

Sometimes however, the error will persist until you fully close and re-open Flagrum. 

The cause of this issue is currently unknown, however due to ability to work around the issue and continue to build the mods, this issue is probably ignorable for the developer unless larger issues result from this.

**Comment by Kizari** [comment] 2023-04-22 01:47
This one has been a real problem for a few versions now. It is very strange and occurs rarely. I have only experienced it myself in development when I accidentally crashed a mod build half way through. All new earcs Flagrum created itself then started giving me this "access denied" message. The only way I could fix it was to manually delete all of these new earcs and then verify files and start over.

This is the only issue I've found to this date regarding the access denied exception that seemed relevant, since this was related to desktop development and newly create files:
https://stackoverflow.com/questions/2007353/unauthorizedaccessexception-on-newly-created-files

Unfortunately since I am unable to reproduce the issue, I can't test if the solution will work. However, I will implement it in the next version anyway in hopes that it will improve the situation if we don't find a way to reproduce in the meantime.

**Comment by Kizari** [comment] 2023-04-22 02:03
This fix has been attempted in Flagrum 1.4.9.

This issue should be reopened if it the fix doesn't work as expected.

**Comment by Kizari** [comment] 2023-04-24 05:11
Reopened as the issue is still affecting some users.

**Comment by Rinual** [comment] 2023-04-24 15:49
![image](https://user-images.githubusercontent.com/108095289/234047618-01923f75-20fd-41ba-bd05-f4a39ce90783.png)

This issue seems to be caused by Windows File Protection, allowing Flagrum as an exception should allow normal operations. 

It seems flagrum is trying access the following areas of the computer:

- %userprofile%\Favorites
- %userprofile%\Documents\MyGames\FINAL FANTASY XV\Steam\76561198037184379\mod\
- %userprofile%\Documents\MyGames\FINAL FANTASY XV\Steam\76561198037184379\savestorage\temp\
- %userprofile%\Documents\My Data Sources\
- RECYCLE.BIN

I'm not positive this is the only issue, as the logs for Flagrum do not match the frequency of the issue, however by allowing Flagrum access, i have yet to have the issue resurface, even though the most recent access is denied messages failed to be logged under protection history.

**Comment by Kizari** [comment] 2023-04-28 04:45
Another attempt has been made to resolve this issue. Since retrying the process was enough to fix the issue for the affected user, I was wondering if perhaps Flagrum was attempting to move the files too soon after first creating them (before Windows could finish registering them with the file system or something). This would potentially explain why it only affects some users, and only some of the time. I've added retry logic to the `File.Move` process in the hopes that a slight delay in the event this occurs will resolve the issue. This attempted fix has been added with Flagrum 1.4.9—this issue should be reopened if the issue still occurs following this update.

**Closed by Kizari** 2023-04-28 04:45 UTC
Labels: bug, low priority, flagrum
