### ISSUE TITLE
getting error when trying to import to blender (using blender 3.3.1)

### ISSUE THREAD

**Issue by keriugi** [Kizari/Flagrum#30] opened 2022-11-26 10:12 UTC
i've been trying to import the cave bat (ma10) to blender with no success. blender throws me an error every time, which i will paste below. it doesn't seem to be a case of not having the armature exported.

possibly of note - this was a model that had an unhandled exception when trying to export with dependencies, and i followed [this workaround](https://github.com/Kizari/Flagrum/issues/23).

image of my folder, shown is the armature and the folder exported with the workaround.
![image](https://user-images.githubusercontent.com/94869852/204083483-2a3522b7-8e4f-4cfe-a61e-330f0c023460.png)

image of the error given by blender
![image](https://user-images.githubusercontent.com/94869852/204083519-0905d1f1-f225-41d9-9703-f23c70dea6a5.png)

**Comment by keriugi** [comment] 2022-11-26 10:19
PASTED FROM BLENDER CONSOLE

Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Flagrum.Blender.Program.<>c__DisplayClass2_3.<Import>b__17(MaterialTexture t) in C:\Code\Flagrum\Flagrum.Blender\Program.cs:line 121
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Flagrum.Blender.Program.Import(String inputPath, String outputPath) in C:\Code\Flagrum\Flagrum.Blender\Program.cs:line 170
   at Flagrum.Blender.Program.Main(String[] args) in C:\Code\Flagrum\Flagrum.Blender\Program.cs:line 23
Traceback (most recent call last):
  File "C:\Users\malic\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Flagrum\import_export\menu.py", line 37, in execute
    mesh_data = Interop.import_mesh(import_context.gfxbin_path)
  File "C:\Users\malic\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Flagrum\import_export\interop.py", line 47, in import_mesh
    import_file = open(tempfile_path, mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\malic\\AppData\\Local\\Temp\\tmpnphxoqzk.json'
Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Flagrum.Blender.Program.<>c__DisplayClass2_3.<Import>b__17(MaterialTexture t) in C:\Code\Flagrum\Flagrum.Blender\Program.cs:line 121
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Flagrum.Blender.Program.Import(String inputPath, String outputPath) in C:\Code\Flagrum\Flagrum.Blender\Program.cs:line 170
   at Flagrum.Blender.Program.Main(String[] args) in C:\Code\Flagrum\Flagrum.Blender\Program.cs:line 23
Traceback (most recent call last):
  File "C:\Users\malic\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Flagrum\import_export\menu.py", line 37, in execute
    mesh_data = Interop.import_mesh(import_context.gfxbin_path)
  File "C:\Users\malic\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Flagrum\import_export\interop.py", line 47, in import_mesh
    import_file = open(tempfile_path, mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\malic\\AppData\\Local\\Temp\\tmp0uml2ofw.json'

**Comment by keriugi** [comment] 2022-11-26 10:23
picture of the texture file names
![image](https://user-images.githubusercontent.com/94869852/204083934-36502524-916d-410b-a40f-e4185b871293.png)

**Comment by Kizari** [comment] 2022-11-26 10:32
The crash in Flagrum.Blender that leads to this error is caused by images having an invalid path in the material.

![image](https://user-images.githubusercontent.com/25322543/204084073-ea23c286-e3d4-487b-9e45-7c6252b7082d.png)

![image](https://user-images.githubusercontent.com/25322543/204084083-9c17eb96-58eb-4509-83d4-4571a25dd383.png)

Specifically, because Flagrum attempts to substring the filename on the `.` character index and because these invalid paths don't have this character, it crashes.

The solution is to simply update the code to cater to SE's incompetence. This will be fixed in a future version.

### Workaround

Until this issue is fixed, the model can be successfully imported into Blender by deleting the problematic material file that was exported with the model. Unfortunately this will prevent materials/textures being automatically imported, but these can still be setup manually for affected models.

**Comment by Kizari** [comment] 2022-11-26 10:33
Likely the same bug as #23 as noted in the original post.

**Comment by Kizari** [comment] 2022-11-29 15:04
This issue is resolved in Flagrum-Blender 1.2.4.

**Closed by Kizari** 2022-11-29 15:04 UTC
Labels: bug, flagrum, blender add-on
