### ISSUE TITLE
Terrain Export crashes Flagrum

### ISSUE THREAD

**Issue by derDinda** [Kizari/Flagrum#122] opened 2024-01-08 17:49 UTC
Terrain exporting crashes Flagrum (latest version 1.5.5.)
Models and Environments work with no problem. But everytime i try to export a Terrain (for example the Leide Terrain in data://environment/world/ebex/heightmap Flagrum starts the process before experiencing a fatal crash.
Nothing is exported other than the 416MB of Common files. 

This happens everytime and i have checked with someone on the Exineris Discord who could reproduce the crash with the same crashlog.

1. Go to 'data://environment/world/ebex/heightmap'
2. Rightclick on ''area_leide_h.exml"
3. Export as Terrain
4. Crash

System.ArgumentNullException
Message: Value cannot be null. (Parameter 'buffer')
Stack Trace:    at System.ArgumentNullException.Throw(String paramName)
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at Flagrum.Core.Graphics.Textures.DirectX.DirectDrawSurface.Write(Stream stream) in C:\Code\Flagrum-Dev\Flagrum.Core\Graphics\Textures\DirectX\DirectDrawSurface.cs:line 104
   at Flagrum.Core.Serialization.BinaryReaderWriterBase.Write() in C:\Code\Flagrum-Dev\Flagrum.Core\Serialization\BinaryReaderWriterBase.cs:line 17
   at Flagrum.Web.Services.TerrainPacker.HebToImages(HeightEntityBinary heb, IEnumerable`1 allowTypes)+MoveNext() in C:\Code\Flagrum-Dev\Flagrum.Web\Features\AssetExplorer\Services\TerrainPacker.cs:line 396
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Flagrum.Web.Services.TerrainPacker.Pack(String uri, String outputPath) in C:\Code\Flagrum-Dev\Flagrum.Web\Features\AssetExplorer\Services\TerrainPacker.cs:line 96
   at Flagrum.Web.Features.AssetExplorer.Export.ExportContextMenu.<>c__DisplayClass25_1.<ExportTerrain>b__2() in C:\Code\Flagrum-Dev\Flagrum.Web\Features\AssetExplorer\Export\ExportContextMenu.razor:line 201
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flagrum.Web.Features.AssetExplorer.Export.ExportContextMenu.<>c__DisplayClass25_0.<<ExportTerrain>b__0>d.MoveNext() in C:\Code\Flagrum-Dev\Flagrum.Web\Features\AssetExplorer\Export\ExportContextMenu.razor:line 201
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2024-01-08_06-04-23-8007_crash_1887372941.txt](https://github.com/Kizari/Flagrum/files/13864498/2024-01-08_06-04-23-8007_crash_1887372941.txt)

**Comment by Kizari** [comment] 2024-01-09 01:05
Hey there. Thanks for your report! I'm able to reproduce on my end as well. Will have this fixed in the next patch.

**Comment by Kizari** [comment] 2024-01-09 01:26
Oops, I'm a clown. This is already known and fixed in 1.5.6 (which is still in development currently). Closing this issue since it's already addressed. 1.5.6 shouldn't be too far away.

Duplicate of #117

**Closed by Kizari** 2024-01-09 01:26 UTC
Labels: bug, flagrum
